name: pushdevelop
on: push

jobs:
  pushdevelop:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
       
      - name: testDefault
      
        run: |
          write-output "Hello World"
          echo "The operating system on the runner is $env:RUNNER_OS."
          echo " name runner is $env:RUNNER_NAME."
          echo " git hub workspace $env:GITHUB_WORKSPACE."
          echo " git hub GITHUB_REPOSITORY $env:GITHUB_REPOSITORY."
          "${GITHUB_WORKSPACE}/.test.ps1"
          
